#!/usr/bin/env bash
# Returning domain information

function info() {
    record_Type=$(dig "$2.$1" ANY +noall +answer | awk '{print $4}' | head -n1)
    destination=$(dig "$2.$1" ANY | awk '/IN/ {print $5}' | head -n1)
    echo "The subdomain $2 is a $record_Type record and points to $destination"
}

sub_domains=("www" "lb-01" "web-01" "web-02")

if [ -z "$2" ]; then
    for sub in "${sub_domains[@]}"; do
        info "$1" "$sub"
    done
else
    info "$1" "$2"
fi